name: Generate Snake Animation

on:
  workflow_dispatch:  # Workflow'u manuel olarak tetikle

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          output_dir: ./dist  # Çıktıyı 'dist' klasörüne kaydet

      - name: Upload Snake Animation as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: ./dist/snake.svg  # Dosya yolunun doğru olduğundan emin ol
