name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün gece 12'de çalıştırır
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake Animation to Profile
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
